### ISSUE TITLE
Inconsistent singular & plural forms.

### ISSUE THREAD

**Issue by nkongsuwan** [trustoverip/vLEI-EGF-v1.0-Interim-Update-Public-Review#1]
### Section Name

6.3.2

### Row number

57

### Question/Comment

In row 57, `The QVI MUST designate a QAR to act on its behalf.` I suggest changing the sentence so that it is consistent with row 50 in 6.3.1.b, that is `The QVI MUST designate a minimum of two QARs to act on its behalf.`

**Comment by nkongsuwan** [comment]
For "Qualified vLEI Issuer Identifer vLEI Credential"

**Comment by kmckenna-gleif** [comment]
Thank you Nuttawut.  The text has been updated to clarify that the QARs that have been identity assured must continue on with Identity Authentication.
