### ISSUE TITLE
Minor typo on row 218 of QVI doc

### ISSUE THREAD

**Issue by psteniusubi** [trustoverip/vLEI-EGF-v1.0-Interim-Update-Public-Review#12]
### Document

Qualified-vLEI-Issuer-Identifer-vLEI-Credential-Governance-Framework

### Section Name

10.1 Schema

### Row number

218

### Question/Comment

218 1. The OOR vLEI Credential MUST be an Authentic Chained Data Container (ACDC) that 

should be

218 1. The **QVI** vLEI Credential MUST be an Authentic Chained Data Container (ACDC) that

**Comment by kmckenna-gleif** [comment]
Thank you Petteri.  The correction has been made.
