### ISSUE TITLE
Can a DAR be one of the LARs?

### ISSUE THREAD

**Issue by nkongsuwan** [trustoverip/vLEI-EGF-v1.0-Interim-Update-Public-Review#2]
### Section Name

6.3.1.f

### Row number

62

### Question/Comment

In row 62, `The DAR SHOULD designate at least three (3) LARs ...`. I suggest clarifying if the DAR can or cannot him/herself be one of the LARs.

**Comment by nkongsuwan** [comment]
For "Legal Entity vLEI Credential"

**Comment by nkongsuwan** [comment]
I would like to also suggest that the EGF clarifies if a DAR of a QVI can also be one of its QARs.

**Comment by kmckenna-gleif** [comment]
Thank you Nuttawut.  Yes, a DAR of a legal entity can decide to become a LAR even in the scenario in which there are enough other authorized signatories or employees to fulfil the role of a LAR.  Of course, in the sole authorized signatory/employee case for a legal entity, the DAR also would be the LAR and the OOR Person.

**Comment by kmckenna-gleif** [comment]
And to your additional comment, yes a DAR of a QVI also can decide to become a QAR.  Notes can be added in the Frameworks to clarify this for both DAR/LAR and DAR/QAR.
