### ISSUE TITLE
Improve clarity for threshold multi-sig for LARs

### ISSUE THREAD

**Issue by nkongsuwan** [trustoverip/vLEI-EGF-v1.0-Interim-Update-Public-Review#3]
### Section Name

6.3.1.f.iv

### Row number

72-73

### Question/Comment

`Using a threshold of all of the LARs would require all usages of the Legal Entity vLEI Credential to be multi-signed by all of the LARs.` 

I suggest improving the clarity of this sentence. For example, what exactly do `using a threshold` and `all usages` mean in  this context?

**Comment by nkongsuwan** [comment]
For "Legal Entity vLEI Credential"

**Comment by kmckenna-gleif** [comment]
Thank you Nuttawut for the comment.  The sentence has been updated to clarify that the expectation is for all presentations of the LE vLEI to be multi-signed by all LARs.  'Any presentation of the Legal Entity vLEI Credential MUST be multi-signed by all of the LARs.'
