### ISSUE TITLE
Change URLs for ACDC and IPEX specifications to ToIP

### ISSUE THREAD

**Issue by nkongsuwan** [trustoverip/vLEI-EGF-v1.0-Interim-Update-Public-Review#4]
### Section Name

9 and 10.2

### Row number

119-120 and 158-162

### Question/Comment

In row 159, the URL points to the IETF KERI specification, not the ACDC protocol specification.

I also suggest updating the links to both ACDC and IPEX specifications from WebOfTrust to ToIP, i.e.,
- https://github.com/trustoverip/tswg-acdc-specification
- https://github.com/trustoverip/tswg-ipex-specification

**Comment by nkongsuwan** [comment]
The URLs are outdated for all documents, not just for this one.

**Comment by kmckenna-gleif** [comment]
Thank you Nuttawut.  All EGF documents are being reviewed and the links to specifications updated to the most current links.
