### ISSUE TITLE
and -> or

### ISSUE THREAD

**Issue by nkongsuwan** [trustoverip/vLEI-EGF-v1.0-Interim-Update-Public-Review#5]
### Section Name

6.3

### Row number

44

### Question/Comment

I suggest changing from `and` to `or` in the sentence on row 44:
"Persons (OOR Persons) `or` Engagement Context Role Persons (ECR Persons) as an"

**Comment by nkongsuwan** [comment]
For "Qualified vLEI Issuer Authorization vLEI Credential"

**Comment by kmckenna-gleif** [comment]
Thank you Nuttawut.  The suggested edit has been made.
