### ISSUE TITLE
Unnecessary double space & empty line

### ISSUE THREAD

**Issue by nkongsuwan** [trustoverip/vLEI-EGF-v1.0-Interim-Update-Public-Review#6]
### Section Name

6.5.2.2.b & 6.5.3.2.c.ii

### Row number

150 & 215

### Question/Comment
Line 150: There is an unnecessary empty line.
Line 215: There is an unnecessary double space between "Legal Entity" and  "AID".

**Comment by kmckenna-gleif** [comment]
Thank you Nuttawut.  All documents in the EGF will be reviewed for correct formatting and spacing before publication.
