### ISSUE TITLE
typo row 74

### ISSUE THREAD

**Issue by guru-barbes** [trustoverip/vLEI-EGF-v1.0-Interim-Update-Public-Review#8]
### Document

Legal-Entity-Official-Organizational-Role-vLEI-Credential-Governance-Framework

### Section Name

OOR Person Idenity Verification

### Row number

74

### Question/Comment

typo: 'on the' is repeated; on the on the ...

**Comment by kmckenna-gleif** [comment]
Thank you guru-barbes.  The repeated text has been deleted.
