### ISSUE TITLE
Monitoring QVI TELs ...

### ISSUE THREAD

**Issue by guru-barbes** [trustoverip/vLEI-EGF-v1.0-Interim-Update-Public-Review#9]
### Document

Qualified-vLEI-Issuer-Authorization-vLEI-Credential-Framework

### Row number

101

### Question/Comment

Does it make sense to recommend a frequency that the Transaction Event Logs must be monitored, i.e. daily or weekly or monthly?

**Comment by kmckenna-gleif** [comment]
Thank you guru-barbes.  The expected frequency of monitoring has been added.
